<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-VA3AMHQ" failures="1" tests="6" name="WrongCredentialsErrorValidation" time="13.426" errors="0" timestamp="2025-02-24T16:49:37 EET">
  <testcase classname="tests.ErrorValidationTest" name="fillWrongCheckoutPageInfo" time="0.559"/>
  <testcase classname="tests.ErrorValidationTest" name="fillWrongCheckoutPageInfo" time="0.512"/>
  <testcase classname="tests.ErrorValidationTest" name="fillWrongCheckoutPageInfo" time="0.535"/>
  <testcase classname="tests.ErrorValidationTest" name="loginLockedUser" time="0.205"/>
  <testcase classname="tests.ErrorValidationTest" name="loginWrongCredentials" time="0.189"/>
  <testcase classname="tests.ErrorValidationTest" name="takeScreenShotOfFailedTest" time="0.001">
    <failure type="java.lang.AssertionError" message="Intentionally failing this test to showcase screenshot feature.">
      <![CDATA[java.lang.AssertionError: Intentionally failing this test to showcase screenshot feature.
at tests.ErrorValidationTest.takeScreenShotOfFailedTest(ErrorValidationTest.java:64)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- takeScreenShotOfFailedTest -->
</testsuite> <!-- WrongCredentialsErrorValidation -->
